#!/bin/bash

# Default behavior: Nuke It All!
NUKE_DS=true
NUKE_ICONM=true
NUKE_APPLE=true
VERBOSE=false

# Parse Args
while getopts "diavh" opt; do
	case $opt in
		d) NUKE_ICONM=false; NUKE_APPLE=false ;;
		i) NUKE_DS=false; NUKE_APPLE=false ;;
		a) NUKE_DS=false; NUKE_ICONM=false ;;
		v) VERBOSE=true ;;
		h)
			echo "Usage: nukefinder.sh [-d] [-i] [-a] [-v] [-h]"
			echo "  -d  Only delete .DS_Store gremlins"
			echo "  -i  Only delete Icon^M weird-ass files"
			echo "  -a  Only delete annoying Apple dotfiles (._*)"
			echo "  -v  Verbose output"
			echo "  -h  Show this help message"
			exit 0
			;;
		\?) echo "Invalid option: -$OPTARG" >&2; exit 1 ;;
	esac
done

echo "🧨 Nuking Finder trash from $(pwd)..."

ds_count=0
iconm_count=0
appledouble_count=0

if $NUKE_DS; then
	$VERBOSE && find . -name ".DS_Store"
	ds_count=$(find . -name ".DS_Store" | wc -l)
	find . -name ".DS_Store" -delete
fi

if $NUKE_ICONM; then
	# Match only files literally named "Icon^M" (that's CR, not wildcard)
	$VERBOSE && find . -type f -name "Icon?" -exec bash -c '
		f=$(basename "$1")
		if [[ "$f" == $'\''Icon\r'\'' ]]; then echo "$1"; fi
	' bash {} \;

	iconm_count=$(find . -type f -name "Icon?" -exec bash -c '
		f=$(basename "$1")
		[[ "$f" == $'\''Icon\r'\'' ]] && echo "$1"
	' bash {} \; | wc -l)

	find . -type f -name "Icon?" -exec bash -c '
		f=$(basename "$1")
		[[ "$f" == $'\''Icon\r'\'' ]] && rm "$1"
	' bash {} \;
fi

if $NUKE_APPLE; then
	$VERBOSE && find . -name "._*"
	appledouble_count=$(find . -name "._*" | wc -l)
	find . -name "._*" -delete
fi

echo "✅ Finder garbage destroyed:"
$NUKE_DS       && echo "   🗑️  .DS_Store       : $ds_count"
$NUKE_ICONM    && echo "   👻 Icon^M           : $iconm_count"
$NUKE_APPLE    && echo "   🧟 ._AppleDouble    : $appledouble_count"